### ISSUE TITLE
Solve runtime exceptions

### ISSUE THREAD

**Issue by massimotisi** [CACAO2017/CACAO2017#39]
After switching to MondeV1, launching the simulation results in an empty window, and clicking on next raises an exception. 

@CACAO2017/lieutenants : the first priority is to arrive to a program that does not raise runtime exceptions during execution.

FYI, the current exception is from @CACAO2017/transformateur-usa.

**Comment by massimotisi** [comment]
@CACAO2017/transformateur-usa: when do you plan to fix your exception?

**Comment by aprage16** [comment]
@massimotisi we will do it today

**Comment by massimotisi** [comment]
Now the current exception is in `Marche.java` from @CACAO2017/distributeur-europe. When do you plan to fix it?

**Comment by wowalid** [comment]
As soon as possible

**Comment by massimotisi** [comment]
Thanks to everybody, I can now close this issue.

From now on *I will not accept pull requests that create runtime exceptions*.
