### ISSUE TITLE
Harmonizing indicator labels

### ISSUE THREAD

**Issue by massimotisi** [CACAO2017/CACAO2017#46]
@CACAO2017/lieutenants: you must agree with each other on a common format for indicator labels

**Comment by antoineroson** [comment]
Cote d’ivoire thinks we should use what was on romu’s mail.
"---> chaque équipe doit ajouter au monde les indicateurs qu'il juge bon d'afficher (cf. exemple dans les constructeurs de Detaillant par exemple. Le nom des indicateurs doit etre précédé du nom de l'acteur : par exemple 6_PROD_COT_solde, 6_PROD_COT_ventes, 6_PROD_COT_stock, …) »

**Comment by aprage16** [comment]
We have the same label than the others

**Comment by massimotisi** [comment]
I see that the majority aligned on the format from the e-mail. I miss @CACAO2017/distributeur-europe and @CACAO2017/producteur-ameriquelatine

**Comment by massimotisi** [comment]
only @CACAO2017/distributeur-europe missing

**Comment by massimotisi** [comment]
@CACAO2017/distributeur-europe: any news on this?
